app/routes/post.py
from flask import Blueprint, render_template, request, redirect, flash, jsonify
from flask_login import login_required
from sqlalchemy import desc, cast, Integer
from ..extensions import db
from ..models.post import Post, Operator_db, Holder_db, Unqualified_db, Cancellation_db
from ..models.user import User
from ..functions import extract_text_from_image, extract_name, extract_conditional_name
from flask_wtf import FlaskForm
from wtforms import SelectField
import os
from PIL import Image
import re

post = Blueprint('post', __name__)

@post.route('/', methods=['POST', 'GET'])
def all():
    post = Post.query.order_by(Post.date.desc()).all()
    return render_template('post/all.html', post=post, user=User)

@post.route('/post/operators_table', methods=['POST', 'GET'])
def operators_table():
    operators = Operator_db.query.order_by(cast(Operator_db.item_journal, Integer).desc()).all()
    return render_template('post/operators_table.html', operator_db=operators, user=User)

@post.route('/post/holders_table', methods=['POST', 'GET'])
def holders_table():
    holders = Holder_db.query.order_by(cast(Holder_db.item_journal, Integer).desc()).all()
    return render_template('post/holders_table.html', holder_db=holders, user=User)

@post.route('/post/unqualified_table', methods=['POST', 'GET'])
def unqualified_table():
    unqualified = Unqualified_db.query.order_by(cast(Unqualified_db.item_journal, Integer).desc()).all()
    return render_template('post/unqualified_table.html', unqualified_db=unqualified, user=User)


@post.route('/post/cancellation_table', methods=['POST', 'GET'])
def cancellation_table():
    cancellation = Cancellation_db.query.order_by(cast(Cancellation_db.item_journal, Integer).desc()).all()
    return render_template('post/cancellation_table.html', cancellation_db=cancellation, user=User)

@post.route('/post/operators_add', methods=['POST', 'GET'])
@login_required
def operators_add():
    if request.method == 'POST':
        item_journal = request.form['item_journal']
        conditional_name = request.form['conditional_name']
        valid_name = request.form['valid_name']
        subordination = request.form['subordination']
        out_number = request.form['out_number']
        in_number = request.form['in_number']
        oid = request.form['oid']
        name = request.form['name']
        type_certificate = request.form['type_certificate']
        status = request.form['status']
        electronic_request = request.form['electronic_request']
        release = request.form['release']
        number_notification = request.form['number_notification']
        date_notification = request.form['date_notification']
        return_certificate = request.form['return_certificate']
        filing_case = request.form['filing_case']
        note = request.form['note']

        new_operator = Operator_db(
            item_journal=item_journal,
            conditional_name=conditional_name,
            valid_name=valid_name,
            subordination=subordination,
            out_number=out_number,
            in_number=in_number,
            oid=oid,
            name=name,
            type_certificate=type_certificate,
            status=status,
            electronic_request=electronic_request,
            release=release,
            number_notification=number_notification,
            date_notification=date_notification,
            return_certificate=return_certificate,
            filing_case=filing_case,
            note=note
        )
        try:
            db.session.add(new_operator)
            db.session.commit()
            return redirect('/post/operators_table')
        except Exception as e:
            return f'Произошла ошибка: {str(e)}'
    else:
        return render_template('post/operators_add.html')

@post.route('/post/holders_add', methods=['POST', 'GET'])
@login_required
def holders_add():
    if request.method == 'POST':
        item_journal = request.form['item_journal']
        conditional_name = request.form['conditional_name']
        valid_name = request.form['valid_name']
        subordination = request.form['subordination']
        out_number = request.form['out_number']
        in_number = request.form['in_number']
        oid = request.form['oid']
        name = request.form['name']
        status = request.form['status']
        electronic_request = request.form['electronic_request']
        release = request.form['release']
        number_notification = request.form['number_notification']
        date_notification = request.form['date_notification']
        return_certificate = request.form['return_certificate']
        filing_case = request.form['filing_case']
        note = request.form['note']

        new_holder = Holder_db(
            item_journal=item_journal,
            conditional_name=conditional_name,
            valid_name=valid_name,
            subordination=subordination,
            out_number=out_number,
            in_number=in_number,
            oid=oid,
            name=name,
            status=status,
            electronic_request=electronic_request,
            release=release,
            number_notification=number_notification,
            date_notification=date_notification,
            return_certificate=return_certificate,
            filing_case=filing_case,
            note=note
        )
        try:
            db.session.add(new_holder)
            db.session.commit()
            return redirect('/post/holders_table')
        except Exception as e:
            return f'Произошла ошибка: {str(e)}'
    else:
        return render_template('post/holders_add.html')

@post.route('/post/unqualified_add', methods=['POST', 'GET'])
@login_required
def unqualified_add():
    if request.method == 'POST':
        item_journal = request.form['item_journal']
        conditional_name = request.form['conditional_name']
        valid_name = request.form['valid_name']
        subordination = request.form['subordination']
        out_number = request.form['out_number']
        in_number = request.form['in_number']
        oid = request.form['oid']
        name = request.form['name']
        status = request.form['status']
        electronic_request = request.form['electronic_request']
        release = request.form['release']
        number_notification = request.form['number_notification']
        date_notification = request.form['date_notification']
        return_certificate = request.form['return_certificate']
        filing_case = request.form['filing_case']
        note = request.form['note']

        new_unqualified = Unqualified_db(
            item_journal=item_journal,
            conditional_name=conditional_name,
            valid_name=valid_name,
            subordination=subordination,
            out_number=out_number,
            in_number=in_number,
            oid=oid,
            name=name,
            status=status,
            electronic_request=electronic_request,
            release=release,
            number_notification=number_notification,
            date_notification=date_notification,
            return_certificate=return_certificate,
            filing_case=filing_case,
            note=note
        )
        try:
            db.session.add(new_unqualified)
            db.session.commit()
            return redirect('/post/unqualified_table')
        except Exception as e:
            return f'Произошла ошибка: {str(e)}'
    else:
        return render_template('post/unqualified_add.html')

@post.route('/post/cancellation_add', methods=['POST', 'GET'])
@login_required
def cancellation_add():
    if request.method == 'POST':
        item_journal = request.form['item_journal']
        conditional_name = request.form['conditional_name']
        valid_name = request.form['valid_name']
        subordination = request.form['subordination']
        out_number = request.form['out_number']
        in_number = request.form['in_number']
        oid = request.form['oid']
        name = request.form['name']
        status = request.form['status']
        date_cancellation = request.form['date_cancellation']
        oid_cancellation = request.form['oid_cancellation']
        number_notification = request.form['number_notification']
        date_notification = request.form['date_notification']
        filing_case = request.form['filing_case']
        note = request.form['note']

        new_cancellation = Cancellation_db(
            item_journal=item_journal,
            conditional_name=conditional_name,
            valid_name=valid_name,
            subordination=subordination,
            out_number=out_number,
            in_number=in_number,
            oid=oid,
            name=name,
            status=status,
            date_cancellation=date_cancellation,
            oid_cancellation=oid_cancellation,
            number_notification=number_notification,
            date_notification=date_notification,
            filing_case=filing_case,
            note=note
        )
        try:
            db.session.add(new_cancellation)
            db.session.commit()
            return redirect('/post/cancellation_table')
        except Exception as e:
            return f'Произошла ошибка: {str(e)}'
    else:
        return render_template('post/cancellation_add.html')

@post.route('/post/<int:item_journal>/operator_update', methods=['POST', 'GET'])
@login_required
def operator_update(item_journal):
    operator_post = Operator_db.query.get(item_journal)
    if request.method == 'POST':
        operator_post.item_journal = request.form.get('item_journal')
        operator_post.conditional_name = request.form.get('conditional_name')

app/routes/user.py
from flask import Blueprint, render_template, redirect, flash, url_for, request
from flask_login import login_user, logout_user
from ..forms import RegistrationForm, LoginForm
from ..extensions import db, bcrypt
from ..models.user import User

user = Blueprint('user', __name__)


@user.route('/user/register', methods=['POST', 'GET'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(name=form.name.data, login=form.login.data, password=hashed_password)
        try:
            db.session.add(user)
            db.session.commit()
            flash(f"Поздравляем, {form.login.data}! Вы успешно зарегистрированы!", "success")
            return redirect(url_for('user.login'))
        except Exception as e:
            print(str(e))
            flash(f"При регистрации произошла ошибка!", "danger")
    return render_template('user/register.html', form=form)

@user.route('/user/login', methods=['POST', 'GET'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(login=form.login.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f"Поздравляем, {form.login.data}! Вы успешно авторизованы!", "success")
            return redirect(next_page) if next_page else redirect(url_for('post.all'))
        else:
            flash(f"Ошибка входа. Проверьте логин и пароль!", "danger")
    return render_template('user/login.html', form=form)


@user.route('/user/logout',  methods=['POST', 'GET'])
def logout():
    logout_user()
    return redirect(url_for('post.all'))

app/templates/main/_flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/main/_footer.html

<div class="d-flex justify-content-between align-items-center">
    <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <img class="footer_img " src="{{ url_for('static', filename='img/88.jpg') }}" alt="88">
    </a>
    <span class="mx-auto">Отделение (обеспечения применения электронной подписи, г. Хабаровск)</span>
        <a href="#" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
    <img class="footer_img " src="{{ url_for('static', filename='img/88.jpg') }}" alt="88">
    </a>
</div>

app/templates/main/_header.html
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="{{ url_for('post.all') }}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
      <img class="header__img" src="{{ url_for('static', filename='img/88.jpg')}}" alt="student">
    </a>

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
      <li><a href="{{ url_for('post.all') }}" class="nav-link px-2 text-secondary"><ya-tr-span data-index="19-0" data-translated="false" data-source-lang="en" data-target-lang="ru" data-value="Home" data-translation="Главная" data-ch="1" data-type="trSpan" style="visibility: inherit !important;">Главная</ya-tr-span></a></li>
    </ul>
    <div class="text-end">
        {% if current_user.is_authenticated %}
        <span>Пользователь: {{ current_user.login }}</span>
             <a href="{{ url_for('user.logout') }}" class="btn btn-outline-dark me-2">Выйти</a>
        {% else %}
            <a href="{{ url_for('user.login') }}" class="btn btn-outline-dark me-2">Вход</a>
            <a href="{{ url_for('user.register') }}" class="btn btn-warning">Зарегистрироваться</a>
        {% endif %}

    </div>
  </div>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{url_for('static', filename='css/libs/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    {% block style %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="page">
    <header class="header">{% include 'main/_header.html'  %}</header>
    <main class="table table-primary">
        {% include 'main/_flash.html' %}
        <h1 class="nav cent justify-content-center border-bottom pb-5 mb-1">{{ self.title() }}</h1>
        {% block content %}{% endblock %}
    </main>
    <footer class="footer py-3">{% include 'main/_footer.html'  %}</footer>
</div>
    <script src="{{ url_for('static', filename='ls/libs/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/app.js')}}"></script>
</body>
</html>