app/models/post.py
from datetime import datetime
from email.policy import default

from ..extensions import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    p_p = db.Column(db.Integer)
    subject = db.Column(db.String(50))
    teacher = db.Column(db.String(50))
    student = db.Column(db.String(50))
    date = db.Column(db.DateTime, default=datetime.utcnow())

class Operator_db(db.Model):
    __tablename__ = 'operator_db'
    id = db.Column(db.Integer, primary_key=True)
    item_journal = db.Column(db.String(20), nullable=True)
    conditional_name = db.Column(db.String(20), nullable=True)
    valid_name = db.Column(db.String(20), nullable=True)
    subordination = db.Column(db.String(20), nullable=True)
    out_number = db.Column(db.String(20), nullable=True)
    in_number = db.Column(db.String(20), nullable=True)
    oid = db.Column(db.String(20), nullable=True, unique=True)
    name = db.Column(db.String(30), nullable=True)
    type_certificate = db.Column(db.String(4), nullable=True)
    status = db.Column(db.String(10), nullable=True)
    electronic_request = db.Column(db.String(20), nullable=True)
    release = db.Column(db.String(20), nullable=True)
    number_notification = db.Column(db.String(20), nullable=True)
    date_notification = db.Column(db.String(20), nullable=True)
    return_certificate = db.Column(db.String(10), nullable=True)
    filing_case = db.Column(db.String(10), nullable=True)
    note = db.Column(db.String(40), nullable=True)

class Holder_db(db.Model):
    __tablename__ = 'holder_db'
    id = db.Column(db.Integer, primary_key=True)
    item_journal = db.Column(db.String(20), nullable=True)
    conditional_name = db.Column(db.String(20), nullable=True)
    valid_name = db.Column(db.String(20), nullable=True)
    subordination = db.Column(db.String(20), nullable=True)
    out_number = db.Column(db.String(20), nullable=True)
    in_number = db.Column(db.String(20), nullable=True)
    oid = db.Column(db.String(20), nullable=True, unique=True)
    name = db.Column(db.String(30), nullable=True)
    status = db.Column(db.String(10), nullable=True)
    electronic_request = db.Column(db.String(20), nullable=True)
    release = db.Column(db.String(20), nullable=True)
    number_notification = db.Column(db.String(20), nullable=True)
    date_notification = db.Column(db.String(20), nullable=True)
    return_certificate = db.Column(db.String(10), nullable=True)
    filing_case = db.Column(db.String(10), nullable=True)
    note = db.Column(db.String(40), nullable=True)

class Unqualified_db(db.Model):
    __tablename__ = 'unqualified_db'
    id = db.Column(db.Integer, primary_key=True)
    item_journal = db.Column(db.String(20), nullable=True)
    conditional_name = db.Column(db.String(20), nullable=True)
    valid_name = db.Column(db.String(20), nullable=True)
    subordination = db.Column(db.String(20), nullable=True)
    out_number = db.Column(db.String(20), nullable=True)
    in_number = db.Column(db.String(20), nullable=True)
    oid = db.Column(db.String(20), nullable=True, unique=True)
    name = db.Column(db.String(30), nullable=True)
    status = db.Column(db.String(10), nullable=True)
    electronic_request = db.Column(db.String(20), nullable=True)
    release = db.Column(db.String(20), nullable=True)
    number_notification = db.Column(db.String(20), nullable=True)
    date_notification = db.Column(db.String(20), nullable=True)
    return_certificate = db.Column(db.String(10), nullable=True)
    filing_case = db.Column(db.String(10), nullable=True)
    note = db.Column(db.String(40), nullable=True)

class Cancellation_db(db.Model):
    __tablename__ = 'cancellation_db'
    id = db.Column(db.Integer, primary_key=True)
    item_journal = db.Column(db.String(20), nullable=True)
    conditional_name = db.Column(db.String(20), nullable=True)
    valid_name = db.Column(db.String(20), nullable=True)
    subordination = db.Column(db.String(20), nullable=True)
    out_number = db.Column(db.String(20), nullable=True)
    in_number = db.Column(db.String(20), nullable=True)
    oid = db.Column(db.String(20), nullable=True, unique=True)
    name = db.Column(db.String(30), nullable=True)
    status = db.Column(db.String(10), nullable=True)
    date_cancellation = db.Column(db.String(20), nullable=True)
    oid_cancellation = db.Column(db.String(20), nullable=True, unique=True)
    number_notification = db.Column(db.String(10), nullable=True)
    date_notification = db.Column(db.String(10), nullable=True)
    filing_case = db.Column(db.String(10), nullable=True)
    note = db.Column(db.String(40), nullable=True)

app/routes/post.py
from flask import Blueprint, render_template, request, redirect, flash, jsonify
from flask_login import login_required
from sqlalchemy import desc, cast, Integer
from ..extensions import db
from ..models.post import Post, Operator_db, Holder_db, Unqualified_db, Cancellation_db
from ..models.user import User
from ..functions import extract_text_from_image, extract_name, extract_conditional_name
from flask_wtf import FlaskForm
from wtforms import SelectField
import os
from PIL import Image
import re

post = Blueprint('post', __name__)

@post.route('/', methods=['POST', 'GET'])
def all():
    post = Post.query.order_by(Post.date.desc()).all()
    return render_template('post/all.html', post=post, user=User)

@post.route('/post/operators_table', methods=['POST', 'GET'])
def operators_table():
    operators = Operator_db.query.order_by(cast(Operator_db.item_journal, Integer).desc()).all()
    return render_template('post/operators_table.html', operator_db=operators, user=User)

@post.route('/post/holders_table', methods=['POST', 'GET'])
def holders_table():
    holders = Holder_db.query.order_by(cast(Holder_db.item_journal, Integer).desc()).all()
    return render_template('post/holders_table.html', holder_db=holders, user=User)

@post.route('/post/unqualified_table', methods=['POST', 'GET'])
def unqualified_table():
    unqualified = Unqualified_db.query.order_by(cast(Unqualified_db.item_journal, Integer).desc()).all()
    return render_template('post/unqualified_table.html', unqualified_db=unqualified, user=User)


@post.route('/post/cancellation_table', methods=['POST', 'GET'])
def cancellation_table():
    cancellation = Cancellation_db.query.order_by(cast(Cancellation_db.item_journal, Integer).desc()).all()
    return render_template('post/cancellation_table.html', cancellation_db=cancellation, user=User)

@post.route('/post/operators_add', methods=['POST', 'GET'])
@login_required
def operators_add():
    if request.method == 'POST':
        item_journal = request.form['item_journal']
        conditional_name = request.form['conditional_name']
        valid_name = request.form['valid_name']
        subordination = request.form['subordination']
        out_number = request.form['out_number']
        in_number = request.form['in_number']
        oid = request.form['oid']
        name = request.form['name']
        type_certificate = request.form['type_certificate']
        status = request.form['status']
        electronic_request = request.form['electronic_request']
        release = request.form['release']
        number_notification = request.form['number_notification']
        date_notification = request.form['date_notification']
        return_certificate = request.form['return_certificate']
        filing_case = request.form['filing_case']
        note = request.form['note']

        new_operator = Operator_db(
            item_journal=item_journal,
            conditional_name=conditional_name,
            valid_name=valid_name,
            subordination=subordination,
            out_number=out_number,
            in_number=in_number,
            oid=oid,
            name=name,
            type_certificate=type_certificate,
            status=status,
            electronic_request=electronic_request,
            release=release,
            number_notification=number_notification,
            date_notification=date_notification,
            return_certificate=return_certificate,
            filing_case=filing_case,
            note=note
        )
        try:
            db.session.add(new_operator)
            db.session.commit()
            return redirect('/post/operators_table')
        except Exception as e:
            return f'Произошла ошибка: {str(e)}'
    else:
        return render_template('post/operators_add.html')

@post.route('/post/holders_add', methods=['POST', 'GET'])
@login_required
def holders_add():
    if request.method == 'POST':
        item_journal = request.form['item_journal']
        conditional_name = request.form['conditional_name']
        valid_name = request.form['valid_name']
        subordination = request.form['subordination']
        out_number = request.form['out_number']
        in_number = request.form['in_number']
        oid = request.form['oid']
        name = request.form['name']
        status = request.form['status']
        electronic_request = request.form['electronic_request']
        release = request.form['release']
        number_notification = request.form['number_notification']
        date_notification = request.form['date_notification']
        return_certificate = request.form['return_certificate']
        filing_case = request.form['filing_case']
        note = request.form['note']

        new_holder = Holder_db(
            item_journal=item_journal,
            conditional_name=conditional_name,
            valid_name=valid_name,
            subordination=subordination,
            out_number=out_number,
            in_number=in_number,
            oid=oid,
            name=name,
            status=status,
            electronic_request=electronic_request,
            release=release,
            number_notification=number_notification,
            date_notification=date_notification,
            return_certificate=return_certificate,
            filing_case=filing_case,
            note=note
        )
        try:
            db.session.add(new_holder)
            db.session.commit()
            return redirect('/post/holders_table')
        except Exception as e:
            return f'Произошла ошибка: {str(e)}'
    else:
        return render_template('post/holders_add.html')

@post.route('/post/unqualified_add', methods=['POST', 'GET'])
@login_required
def unqualified_add():
    if request.method == 'POST':
        item_journal = request.form['item_journal']
        conditional_name = request.form['conditional_name']
        valid_name = request.form['valid_name']
        subordination = request.form['subordination']
        out_number = request.form['out_number']
        in_number = request.form['in_number']
        oid = request.form['oid']
        name = request.form['name']
        status = request.form['status']
        electronic_request = request.form['electronic_request']
        release = request.form['release']
        number_notification = request.form['number_notification']
        date_notification = request.form['date_notification']
        return_certificate = request.form['return_certificate']
        filing_case = request.form['filing_case']
        note = request.form['note']

        new_unqualified = Unqualified_db(
            item_journal=item_journal,
            conditional_name=conditional_name,
            valid_name=valid_name,
            subordination=subordination,
            out_number=out_number,
            in_number=in_number,
            oid=oid,
            name=name,
            status=status,
            electronic_request=electronic_request,
            release=release,
            number_notification=number_notification,
            date_notification=date_notification,
            return_certificate=return_certificate,
            filing_case=filing_case,
            note=note
        )
        try:
            db.session.add(new_unqualified)
            db.session.commit()
            return redirect('/post/unqualified_table')
        except Exception as e:
            return f'Произошла ошибка: {str(e)}'
    else:
        return render_template('post/unqualified_add.html')

@post.route('/post/cancellation_add', methods=['POST', 'GET'])
@login_required
def cancellation_add():
    if request.method == 'POST':
        item_journal = request.form['item_journal']
        conditional_name = request.form['conditional_name']
        valid_name = request.form['valid_name']
        subordination = request.form['subordination']
        out_number = request.form['out_number']
        in_number = request.form['in_number']
        oid = request.form['oid']
        name = request.form['name']
        status = request.form['status']
        date_cancellation = request.form['date_cancellation']
        oid_cancellation = request.form['oid_cancellation']
        number_notification = request.form['number_notification']
        date_notification = request.form['date_notification']
        filing_case = request.form['filing_case']
        note = request.form['note']

        new_cancellation = Cancellation_db(
            item_journal=item_journal,
            conditional_name=conditional_name,
            valid_name=valid_name,
            subordination=subordination,
            out_number=out_number,
            in_number=in_number,
            oid=oid,
            name=name,
            status=status,
            date_cancellation=date_cancellation,
            oid_cancellation=oid_cancellation,
            number_notification=number_notification,
            date_notification=date_notification,
            filing_case=filing_case,
            note=note
        )
        try:
            db.session.add(new_cancellation)
            db.session.commit()
            return redirect('/post/cancellation_table')
        except Exception as e:
            return f'Произошла ошибка: {str(e)}'
    else:
        return render_template('post/cancellation_add.html')

@post.route('/post/<int:item_journal>/operator_update', methods=['POST', 'GET'])
@login_required
def operator_update(item_journal):
    operator_post = Operator_db.query.get(item_journal)
    if request.method == 'POST':
        operator_post.item_journal = request.form.get('item_journal')
        operator_post.conditional_name = request.form.get('conditional_name')

app/templates/post/all.html
{% extends 'main/base.html' %}

{% block title %}База данных регистрации СКП ЭП{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/table.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/font-awesome.min.css') }}">
    <style>
        /* Стили для кнопок */

         .button-container {
            display: flex;
            flex-direction: row;
            justify-content: center; /* Распределяем кнопки по центру */
        }
    </style>
{% endblock %}

{% block content %}
<body>
    <div class="content button-container">
        <a class="btn btn-outline-dark me-2" type="button" href="{{url_for('post.operators_table')}}">Таблица операторов</a>
        <a class="btn btn-outline-dark me-2" type="button" href="{{url_for('post.holders_table')}}">Таблица держателей</a>
        <a class="btn btn-outline-dark me-2" type="button" href="{{url_for('post.unqualified_table')}}">Таблица неквала</a>
        <a class="btn btn-outline-dark me-2" type="button" href="{{url_for('post.cancellation_table')}}">Таблица аннулирования</a>
        <a class="btn btn-outline-primary me-2" type="button" href="{{url_for('post.operators_add')}}">Новая запись оператора</a>
        <a class="btn btn-outline-primary me-2" type="button" href="{{url_for('post.holders_add')}}">Новая запись держателя</a>
        <a class="btn btn-outline-primary me-2" type="button" href="{{url_for('post.unqualified_add')}}">Новая запись неквала</a>
        <a class="btn btn-outline-primary me-2" type="button" href="{{url_for('post.cancellation_add')}}">Новая запись аннулирования</a>
    </div>
</body>
{% endblock %}

app/templates/post/cancellation_add.html
{% extends 'main/base.html' %}

{% block title %}
Добавление записи аннулирования
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/table.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/font-awesome.min.css') }}">
{% endblock %}

{% block content %}
<h1>Загрузить из файла</h1>

<form id="uploadFileForm" enctype="multipart/form-data">
    <input type="file" name="file" id="fileInput">
    <button type="button" class="btn btn-outline-primary me-2" onclick="uploadFile()">Загрузить</button>
</form>

<form method="post" class="form-control" id="uploadForm" enctype="multipart/form-data">
    <input type="text" name="item_journal" placeholder="Пункт по журналу" class="form-control"><br>
    <input type="text" name="conditional_name" id="conditional_name" placeholder="Условное наименование" class="form-control" ><br>
    <input type="text" name="valid_name" placeholder="Действительное наименование" class="form-control" ><br>
    <input type="text" name="subordination" placeholder="Подчиненность" class="form-control" ><br>
    <input type="text" name="out_number" placeholder="Исходящий номер" class="form-control" ><br>
    <input type="text" name="in_number" placeholder="Входящий номер" class="form-control" ><br>
    <input type="text" name="oid" placeholder="OID" class="form-control" ><br>
    <input type="text" name="name" id="name" placeholder="Фамилия Имя Отчество" class="form-control" ><br>
    <input type="text" name="status" placeholder="Статус" class="form-control" ><br>
    <input type="text" name="date_cancellation" placeholder="Дата аннулирования" class="form-control" ><br>
    <input type="text" name="oid_cancellation" placeholder="OID аннулированния" class="form-control" ><br>
    <input type="text" name="number_notification" placeholder="Номер уведомления" class="form-control" ><br>
    <input type="text" name="date_notification" placeholder="Дата уведомления" class="form-control" ><br>
    <input type="text" name="filing_case" placeholder="Подшивка в дело" class="form-control" ><br>
    <input type="text" name="note" placeholder="Примечание" class="form-control" ><br>
    <button class="btn btn-success" type="submit">Добавить</button>
</form>

<script>
    function uploadFile() {
        const fileInput = document.getElementById('fileInput');
        const file = fileInput.files[0];

        if (!file) {
            alert("Выберите файл!");
            return;
        }

        const formData = new FormData();
        formData.append('file', file);

        // Отправляем файл на сервер
        fetch('/post/upload', {
            method: 'POST',
            body: formData
        })
        .then(response => response.json())
        .then(data => {
            // Заполняем поля name и conditional_name
            if (data.name) {
                document.getElementById('name').value = data.name;
            }
            if (data.conditional_name) {
                document.getElementById('conditional_name').value = data.conditional_name;
            }
        })
        .catch(error => {
            console.error("Ошибка:", error);
        });
    }
</script>
{% endblock %}

app/templates/post/cancellation_table.html
{% extends 'main/base.html' %}

{% block title %}
Таблица аннулирования
{% endblock %}

{% block style %}
<style>
    body, html {
        margin: 0;
        padding: 0;
        height: 100%;
        font-family: Arial, sans-serif;
    }

    .container {
        display: flex;
        flex-direction: column;
        height: 100%;
    }

    .table-container {
        flex: 1;
        display: flex;
        justify-content: center;
        align-items: flex-start; /* Выравнивание по верхнему краю */
        overflow-x: auto;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
    }

    th, td {
        border: 1px solid #ddd;
        text-align: left;
    }

    th {
        background-color: #f4f4f4;
        position: sticky;
        top: 0; /* Фиксация заголовка таблицы при прокрутке */
        z-index: 10;
    }
</style>
{% endblock %}

{% block content %}
<table class="table table-bordered border-primary">
    <thead>
        <tr>
            <th scope="col">Пункт по журналу</th>
            <th scope="col">Условное наименование</th>
            <th scope="col">Действительное наименование</th>
            <th scope="col">Подчиненность</th>
            <th scope="col">Исх. номер</th>
            <th scope="col">Вх. номер</th>
            <th scope="col">OID</th>
            <th scope="col">Фамилия Имя Отчество</th>
            <th scope="col">Статус</th>
            <th scope="col">Дата аннулирования</th>
            <th scope="col">OID аннулирования</th>
            <th scope="col">Номер уведомления</th>
            <th scope="col">Дата уведомления</th>
            <th scope="col">Дело</th>
            <th scope="col">Примечание</th>
            <th scope="col">Действие</th>
        </tr>
    </thead>
    <tbody>
    {% for user in cancellation_db %}
        <tr>
            <td>{{ user.item_journal }}</td>
            <td>{{ user.conditional_name }}</td>
            <td>{{ user.valid_name }}</td>
            <td>{{ user.subordination }}</td>
            <td>{{ user.out_number }}</td>
            <td>{{ user.in_number }}</td>
            <td>{{ user.oid }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.status }}</td>
            <td>{{ user.date_cancellation }}</td>
            <td>{{ user.oid_cancellation }}</td>
            <td>{{ user.number_notification }}</td>
            <td>{{ user.date_notification }}</td>
            <td>{{ user.filing_case }}</td>
            <td>{{ user.note }}</td>
            <td>
                <a href="{{ url_for('post.cancellation_update', item_journal=user.id) }}" class="btn btn-sm btn-secondary">Ред.</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/post/cancellation_update.html
{% extends 'main/base.html' %}

{% block title %}
Редактирование записи аннулирования № {{ cancellation.item_journal }}
{% endblock %}

{% block content %}

<form method="post" class="form-control">
    <input value="{{ cancellation.item_journal }}" type="text" name="item_journal" placeholder="Пункт по журналу" class="form-control"><br>
    <input value="{{ cancellation.conditional_name }}" type="text" name="conditional_name" placeholder="Условное наименование" class="form-control" ><br>
    <input value="{{ cancellation.valid_name }}" type="text" name="valid_name" placeholder="Действительное наименование" class="form-control" ><br>
    <input value="{{ cancellation.subordination }}" type="text" name="subordination" placeholder="Подчиненность" class="form-control" ><br>
    <input value="{{ cancellation.out_number }}" type="text" name="out_number" placeholder="Исходящий номер" class="form-control" ><br>
    <input value="{{ cancellation.in_number }}" type="text" name="in_number" placeholder="Входящий номер" class="form-control" ><br>
    <input value="{{ cancellation.oid }}" type="text" name="oid" placeholder="OID" class="form-control" ><br>
    <input value="{{ cancellation.name }}" type="text" name="name" placeholder="Фамилия Имя Отчество" class="form-control" ><br>
    <input value="{{ cancellation.status }}" type="text" name="status" placeholder="Статус" class="form-control" ><br>
    <input value="{{ cancellation.date_cancellation }}" type="text" name="date_cancellation" placeholder="Дата аннулирования" class="form-control" ><br>
    <input value="{{ cancellation.oid_cancellation }}" type="text" name="oid_cancellation" placeholder="OID аннулированния" class="form-control" ><br>
    <input value="{{ cancellation.number_notification }}" type="text" name="number_notification" placeholder="Номер уведомления" class="form-control" ><br>
    <input value="{{ cancellation.date_notification }}" type="text" name="date_notification" placeholder="Дата уведомления" class="form-control" ><br>
    <input value="{{ cancellation.date_notification }}" type="text" name="filing_case" placeholder="Подшивка в дело" class="form-control" ><br>
    <input value="{{ cancellation.note }}" type="text" name="note" placeholder="Примечание" class="form-control" ><br>
    <input value="Обновить" type="submit" class="btn btn-success">
</form>
{% endblock %}

app/templates/post/holder_update.html
{% extends 'main/base.html' %}

{% block title %}
Редактирование записи держателя № {{ holder.item_journal }}
{% endblock %}

{% block content %}

<form method="post" class="form-control">
    <input value="{{ holder.item_journal }}"  type="text" name="item_journal" placeholder="Пункт по журналу" class="form-control"><br>
    <input value="{{ holder.conditional_name }}" type="text" name="conditional_name" placeholder="Условное наименование" class="form-control" ><br>
    <input value="{{ holder.valid_name }}" type="text" name="valid_name" placeholder="Действительное наименование" class="form-control" ><br>
    <input value="{{ holder.subordination }}" type="text" name="subordination" placeholder="Подчиненность" class="form-control" ><br>
    <input value="{{ holder.out_number }}" type="text" name="out_number" placeholder="Исходящий номер" class="form-control" ><br>
    <input value="{{ holder.in_number }}" type="text" name="in_number" placeholder="Входящий номер" class="form-control" ><br>
    <input value="{{ holder.oid }}" type="text" name="oid" placeholder="OID" class="form-control" ><br>
    <input value="{{ holder.name }}" type="text" name="name" placeholder="Фамилия Имя Отчество" class="form-control" ><br>
    <input value="{{ holder.status }}" type="text" name="status" placeholder="Статус" class="form-control" ><br>
    <input value="{{ holder.electronic_request }}" type="text" name="electronic_request" placeholder="Поступление электронного запроса" class="form-control" ><br>
    <input value="{{ holder.release }}" type="text" name="release" placeholder="Выпуск СКПЭП" class="form-control" ><br>
    <input value="{{ holder.number_notification }}" type="text" name="number_notification" placeholder="Номер уведомления" class="form-control" ><br>
    <input value="{{ holder.date_notification }}" type="text" name="date_notification" placeholder="Дата уведомления" class="form-control" ><br>
    <input value="{{ holder.return_certificate }}" type="text" name="return_certificate" placeholder="Возврат СКПЭП" class="form-control" ><br>
    <input value="{{ holder.filing_case }}" type="text" name="filing_case" placeholder="Подшивка в дело" class="form-control" ><br>
    <input value="{{ holder.note }}" type="text" name="note" placeholder="Примечание" class="form-control" ><br>
    <input value="Обновить" type="submit" class="btn btn-success">
</form>
{% endblock %}

app/templates/post/operators_table.html
{% extends 'main/base.html' %}

{% block title %}
Таблица операторов
{% endblock %}

{% block style %}
<style>
    body, html {
        margin: 0;
        padding: 0;
        height: 100%;
        font-family: Arial, sans-serif;
    }

    .container {
        display: flex;
        flex-direction: column;
        height: 100%;
    }

    .table-container {
        flex: 1;
        display: flex;
        justify-content: center;
        align-items: flex-start; /* Выравнивание по верхнему краю */
        overflow-x: auto;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
    }

    th, td {
        border: 1px solid #ddd;
        text-align: left;
    }

    th {
        background-color: #f4f4f4;
        position: sticky;
        top: 0; /* Фиксация заголовка таблицы при прокрутке */
        z-index: 10;
    }
</style>
{% endblock %}

{% block content %}
<table class="table table-bordered border-primary">
    <thead>
        <tr>
            <th scope="col">Пункт по журналу</th>
            <th scope="col">Условное наименование</th>
            <th scope="col">Действительное наименование</th>
            <th scope="col">Подчиненность</th>
            <th scope="col">Исх. номер</th>
            <th scope="col">Вх. номер</th>
            <th scope="col">OID</th>
            <th scope="col">Фамилия Имя Отчество</th>
            <th scope="col">Тип</th>
            <th scope="col">Статус</th>
            <th scope="col">Поступление электронного запроса</th>
            <th scope="col">Выпуск СКПЭП</th>
            <th scope="col">Номер уведомления</th>
            <th scope="col">Дата уведомления</th>
            <th scope="col">Возврат СКПЭП</th>
            <th scope="col">Дело</th>
            <th scope="col">Примечание</th>
            <th scope="col">Действие</th>
        </tr>
    </thead>
    <tbody>
        {% for user in operator_db %}
        <tr>
            <td>{{ user.item_journal }}</td>
            <td>{{ user.conditional_name }}</td>
            <td>{{ user.valid_name }}</td>
            <td>{{ user.subordination }}</td>
            <td>{{ user.out_number }}</td>
            <td>{{ user.in_number }}</td>
            <td>{{ user.oid }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.type_certificate }}</td>
            <td>{{ user.status }}</td>
            <td>{{ user.electronic_request }}</td>
            <td>{{ user.release }}</td>
            <td>{{ user.number_notification }}</td>
            <td>{{ user.date_notification }}</td>
            <td>{{ user.return_certificate }}</td>
            <td>{{ user.filing_case }}</td>
            <td>{{ user.note }}</td>
            <td>
                <a href="{{ url_for('post.operator_update', item_journal=user.id) }}" class="btn btn-sm btn-secondary">Ред.</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/post/update.html
{% extends 'main/base.html' %}

{% block title %}Редактирование темы {{ post.id }}{% endblock %}

{% block content %}
<form method="post" class="form-control d-flex fex-column gap-2">
    <input value="{{ post.p_p }}" name="p_p" type="text"  placeholder="п/п" class="form-control">
    <input value="{{ post.teacher }}" name="teacher" type="text"  placeholder="ФИО преподавателя" class="form-control">
    <input value="{{ post.subject }}" name="subject" type="text"  placeholder="Тема" class="form-control">
    <input value="{{ post.student }}" name="student" type="text"  placeholder="ФИО студента" class="form-control">
    <input value="Обновить" type="submit" class="btn btn-success">
</form>
{% endblock %}